<?php
/**
 * Reference.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\ReferenceModule\Entity\Base;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Validator\Constraints as Assert;
use RK\ReferenceModule\Traits\EntityWorkflowTrait;
use RK\ReferenceModule\Traits\StandardFieldsTrait;

use RuntimeException;
use ServiceUtil;
use Zikula\Core\Doctrine\EntityAccess;

/**
 * Entity class that defines the entity structure and behaviours.
 *
 * This is the base entity class for attached image entities.
 * The following annotation marks it as a mapped superclass so subclasses
 * inherit orm properties.
 *
 * @ORM\MappedSuperclass
 *
 * @abstract
 */
abstract class AbstractAttachedImageEntity extends EntityAccess
{
    /**
     * Hook entity workflow field and behaviour.
     */
    use EntityWorkflowTrait;

    /**
     * Hook standard fields behaviour embedding createdBy, updatedBy, createdDate, updatedDate fields.
     */
    use StandardFieldsTrait;

    /**
     * @var string The tablename this object maps to
     */
    protected $_objectType = 'attachedImage';
    
    /**
     * @Assert\Type(type="bool")
     * @var boolean Option to bypass validation if needed
     */
    protected $_bypassValidation = false;
    
    /**
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(type="integer", unique=true)
     * @var integer $id
     */
    protected $id = 0;
    
    /**
     * the current workflow state
     * @ORM\Column(length=20)
     * @Assert\NotBlank()
     * @Assert\Choice(callback="getWorkflowStateAllowedValues", multiple=false)
     * @var string $workflowState
     */
    protected $workflowState = 'initial';
    
    /**
     * Select in which language the activity should be shown. Select "all" for every language.
     * @ORM\Column(length=255)
     * @Assert\NotNull()
     * @Assert\Regex(pattern="/\s/", match=false, message="This value must not contain space chars.")
     * @Assert\Length(min="0", max="255")
     * @Assert\Locale()
     * @var string $displayLanguage
     */
    protected $displayLanguage = '';
    
    /**
     * a title for the image
     * @ORM\Column(length=255)
     * @Assert\NotBlank()
     * @Assert\Length(min="0", max="255")
     * @var string $title
     */
    protected $title = '';
    
    /**
     * Added image meta data array.
     *
     * @ORM\Column(type="array")
     * @Assert\Type(type="array")
     * @var array $addedImageMeta
     */
    protected $addedImageMeta = [];
    
    /**
     * @ORM\Column(length=255)
     * @Assert\NotBlank()
     * @Assert\Length(min="0", max="255")
     * @Assert\File(
        mimeTypes = {"image/*"}
     * )
     * @Assert\Image(
     * )
     * @var string $addedImage
     */
    protected $addedImage = null;
    
    /**
     * Full added image path as url.
     *
     * @Assert\Type(type="string")
     * @var string $addedImageUrl
     */
    protected $addedImageUrl = '';
    
    /**
     * tell something about what the image is showing or standing for.
     * @ORM\Column(type="text", length=1000)
     * @Assert\NotNull()
     * @Assert\Length(min="0", max="1000")
     * @var text $shortDescription
     */
    protected $shortDescription = '';
    
    
    /**
     * Bidirectional - One activity [attached image] has many attachedImages [activities] (INVERSE SIDE).
     *
     * @ORM\OneToMany(targetEntity="RK\ReferenceModule\Entity\ActivityEntity", mappedBy="activity")
     * @ORM\JoinTable(name="rk_refere_activityattachedimages")
     * @var \RK\ReferenceModule\Entity\ActivityEntity[] $attachedImages
     */
    protected $attachedImages = null;
    
    
    /**
     * AttachedImageEntity constructor.
     *
     * Will not be called by Doctrine and can therefore be used
     * for own implementation purposes. It is also possible to add
     * arbitrary arguments as with every other class method.
     *
     * @param TODO
     */
    public function __construct()
    {
        $this->initWorkflow();
        $this->attachedImages = new ArrayCollection();
    }
    
    /**
     * Returns the _object type.
     *
     * @return string
     */
    public function get_objectType()
    {
        return $this->_objectType;
    }
    
    /**
     * Sets the _object type.
     *
     * @param string $_objectType
     *
     * @return void
     */
    public function set_objectType($_objectType)
    {
        $this->_objectType = $_objectType;
    }
    
    /**
     * Returns the _bypass validation.
     *
     * @return boolean
     */
    public function get_bypassValidation()
    {
        return $this->_bypassValidation;
    }
    
    /**
     * Sets the _bypass validation.
     *
     * @param boolean $_bypassValidation
     *
     * @return void
     */
    public function set_bypassValidation($_bypassValidation)
    {
        $this->_bypassValidation = $_bypassValidation;
    }
    
    
    /**
     * Returns the id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }
    
    /**
     * Sets the id.
     *
     * @param integer $id
     *
     * @return void
     */
    public function setId($id)
    {
        $this->id = intval($id);
    }
    
    /**
     * Returns the workflow state.
     *
     * @return string
     */
    public function getWorkflowState()
    {
        return $this->workflowState;
    }
    
    /**
     * Sets the workflow state.
     *
     * @param string $workflowState
     *
     * @return void
     */
    public function setWorkflowState($workflowState)
    {
        $this->workflowState = isset($workflowState) ? $workflowState : '';
    }
    
    /**
     * Returns the display language.
     *
     * @return string
     */
    public function getDisplayLanguage()
    {
        return $this->displayLanguage;
    }
    
    /**
     * Sets the display language.
     *
     * @param string $displayLanguage
     *
     * @return void
     */
    public function setDisplayLanguage($displayLanguage)
    {
        $this->displayLanguage = isset($displayLanguage) ? $displayLanguage : '';
    }
    
    /**
     * Returns the title.
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }
    
    /**
     * Sets the title.
     *
     * @param string $title
     *
     * @return void
     */
    public function setTitle($title)
    {
        $this->title = isset($title) ? $title : '';
    }
    
    /**
     * Returns the added image.
     *
     * @return string
     */
    public function getAddedImage()
    {
        return $this->addedImage;
    }
    
    /**
     * Sets the added image.
     *
     * @param string $addedImage
     *
     * @return void
     */
    public function setAddedImage($addedImage)
    {
        $this->addedImage = isset($addedImage) ? $addedImage : '';
    }
    
    /**
     * Returns the added image url.
     *
     * @return string
     */
    public function getAddedImageUrl()
    {
        return $this->addedImageUrl;
    }
    
    /**
     * Sets the added image url.
     *
     * @param string $addedImageUrl
     *
     * @return void
     */
    public function setAddedImageUrl($addedImageUrl)
    {
        $this->addedImageUrl = isset($addedImageUrl) ? $addedImageUrl : '';
    }
    
    /**
     * Returns the added image meta.
     *
     * @return array
     */
    public function getAddedImageMeta()
    {
        return $this->addedImageMeta;
    }
    
    /**
     * Sets the added image meta.
     *
     * @param array $addedImageMeta
     *
     * @return void
     */
    public function setAddedImageMeta($addedImageMeta = [])
    {
        $this->addedImageMeta = isset($addedImageMeta) ? $addedImageMeta : '';
    }
    
    /**
     * Returns the short description.
     *
     * @return text
     */
    public function getShortDescription()
    {
        return $this->shortDescription;
    }
    
    /**
     * Sets the short description.
     *
     * @param text $shortDescription
     *
     * @return void
     */
    public function setShortDescription($shortDescription)
    {
        $this->shortDescription = isset($shortDescription) ? $shortDescription : '';
    }
    
    
    /**
     * Returns the attached images.
     *
     * @return \RK\ReferenceModule\Entity\ActivityEntity[]
     */
    public function getAttachedImages()
    {
        return $this->attachedImages;
    }
    
    /**
     * Sets the attached images.
     *
     * @param \RK\ReferenceModule\Entity\ActivityEntity[] $attachedImages
     *
     * @return void
     */
    public function setAttachedImages($attachedImages)
    {
        foreach ($attachedImages as $activitySingle) {
            $this->addAttachedImages($activitySingle);
        }
    }
    
    /**
     * Adds an instance of \RK\ReferenceModule\Entity\ActivityEntity to the list of attached images.
     *
     * @param \RK\ReferenceModule\Entity\ActivityEntity $activity The instance to be added to the collection
     *
     * @return void
     */
    public function addAttachedImages(\RK\ReferenceModule\Entity\ActivityEntity $activity)
    {
        $this->attachedImages->add($activity);
        $activity->setActivity($this);
    }
    
    /**
     * Removes an instance of \RK\ReferenceModule\Entity\ActivityEntity from the list of attached images.
     *
     * @param \RK\ReferenceModule\Entity\ActivityEntity $activity The instance to be removed from the collection
     *
     * @return void
     */
    public function removeAttachedImages(\RK\ReferenceModule\Entity\ActivityEntity $activity)
    {
        $this->attachedImages->removeElement($activity);
        $activity->setActivity(null);
    }
    
    
    
    /**
     * Returns the formatted title conforming to the display pattern
     * specified for this entity.
     *
     * @return string The display title
     */
    public function getTitleFromDisplayPattern()
    {
        $listHelper = ServiceUtil::get('rk_reference_module.listentries_helper');
    
        $formattedTitle = ''
                . $this->getTitle();
    
        return $formattedTitle;
    }
    
    
    /**
     * Returns a list of possible choices for the workflowState list field.
     * This method is used for validation.
     *
     * @return array List of allowed choices
     */
    public static function getWorkflowStateAllowedValues()
    {
        $container = ServiceUtil::get('service_container');
        $helper = $container->get('rk_reference_module.listentries_helper');
        $listEntries = $helper->getWorkflowStateEntriesForAttachedImage();
    
        $allowedValues = ['initial'];
        foreach ($listEntries as $entry) {
            $allowedValues[] = $entry['value'];
        }
    
        return $allowedValues;
    }
    
    /**
     * Start validation and raise exception if invalid data is found.
     *
     * @return boolean Whether everything is valid or not
     */
    public function validate()
    {
        if (true === $this->_bypassValidation) {
            return true;
        }
    
        $validator = ServiceUtil::get('validator');
        $errors = $validator->validate($this);
    
        if (count($errors) > 0) {
            $flashBag = ServiceUtil::get('session')->getFlashBag();
            foreach ($errors as $error) {
                $flashBag->add('error', $error->getMessage());
            }
    
            return false;
        }
    
        return true;
    }
    
    /**
     * Return entity data in JSON format.
     *
     * @return string JSON-encoded data
     */
    public function toJson()
    {
        return json_encode($this->toArray());
    }
    
    /**
     * Creates url arguments array for easy creation of display urls.
     *
     * @return array The resulting arguments list
     */
    public function createUrlArgs()
    {
        $args = [];
    
        $args['id'] = $this['id'];
    
        if (property_exists($this, 'slug')) {
            $args['slug'] = $this['slug'];
        }
    
        return $args;
    }
    
    /**
     * Create concatenated identifier string (for composite keys).
     *
     * @return String concatenated identifiers
     */
    public function createCompositeIdentifier()
    {
        $itemId = $this['id'];
    
        return $itemId;
    }
    
    /**
     * Determines whether this entity supports hook subscribers or not.
     *
     * @return boolean
     */
    public function supportsHookSubscribers()
    {
        return true;
    }
    
    /**
     * Return lower case name of multiple items needed for hook areas.
     *
     * @return string
     */
    public function getHookAreaPrefix()
    {
        return 'rkreferencemodule.ui_hooks.attachedimages';
    }
    
    /**
     * Returns an array of all related objects that need to be persisted after clone.
     * 
     * @param array $objects The objects are added to this array. Default: []
     * 
     * @return array of entity objects
     */
    public function getRelatedObjectsToPersist(&$objects = []) 
    {
        return [];
    }
    
    /**
     * ToString interceptor implementation.
     * This method is useful for debugging purposes.
     *
     * @return string The output string for this entity
     */
    public function __toString()
    {
        return 'Attached image ' . $this->createCompositeIdentifier() . ': ' . $this->getTitleFromDisplayPattern();
    }
    
    /**
     * Clone interceptor implementation.
     * This method is for example called by the reuse functionality.
     * Performs a quite simple shallow copy.
     *
     * See also:
     * (1) http://docs.doctrine-project.org/en/latest/cookbook/implementing-wakeup-or-clone.html
     * (2) http://www.php.net/manual/en/language.oop5.cloning.php
     * (3) http://stackoverflow.com/questions/185934/how-do-i-create-a-copy-of-an-object-in-php
     */
    public function __clone()
    {
        // if the entity has no identity do nothing, do NOT throw an exception
        if (!($this->id)) {
            return;
        }
    
        // otherwise proceed
    
        // unset identifiers
        $this->setId(0);
    
        // reset workflow
        $this->resetWorkflow();
    
        // reset upload fields
        $this->setAddedImage(null);
        $this->setAddedImageMeta([]);
        $this->setAddedImageUrl('');
    
        $this->setCreatedBy(null);
        $this->setCreatedDate(null);
        $this->setUpdatedBy(null);
        $this->setUpdatedDate(null);
    
    }
}
