## YAML Override template
## original/file.tpl: override/file.tpl
---
system/BlocksModule/Resources/views/Block/Extmenu/topnav.tpl: themes/RK/IndausTheme/Resources/views/modules/ZikulaBlocksModule/Block/Extmenu/topnav.tpl
