<?php
/**
 * Info.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.1 (http://modulestudio.de).
 */

namespace RK\InfoModule\TaggedObjectMeta;

use RK\InfoModule\TaggedObjectMeta\Base\AbstractRKInfoModule;

/**
 * This class provides object meta data for the Tag module.
 */
class RKInfoModule extends AbstractRKInfoModule
{
    // feel free to extend the tag support here
}
