<?php
/**
 * Reference.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\ReferenceModule\Base;

/**
 * Events definition base class.
 */
abstract class AbstractReferenceEvents
{
    /**
     * The rkreferencemodule.attachedimage_post_load event is thrown when attached images
     * are loaded from the database.
     *
     * The event listener receives an
     * RK\ReferenceModule\Event\FilterAttachedImageEvent instance.
     *
     * @see RK\ReferenceModule\Listener\EntityLifecycleListener::postLoad()
     * @var string
     */
    const ATTACHEDIMAGE_POST_LOAD = 'rkreferencemodule.attachedimage_post_load';
    
    /**
     * The rkreferencemodule.attachedimage_pre_persist event is thrown before a new attached image
     * is created in the system.
     *
     * The event listener receives an
     * RK\ReferenceModule\Event\FilterAttachedImageEvent instance.
     *
     * @see RK\ReferenceModule\Listener\EntityLifecycleListener::prePersist()
     * @var string
     */
    const ATTACHEDIMAGE_PRE_PERSIST = 'rkreferencemodule.attachedimage_pre_persist';
    
    /**
     * The rkreferencemodule.attachedimage_post_persist event is thrown after a new attached image
     * has been created in the system.
     *
     * The event listener receives an
     * RK\ReferenceModule\Event\FilterAttachedImageEvent instance.
     *
     * @see RK\ReferenceModule\Listener\EntityLifecycleListener::postPersist()
     * @var string
     */
    const ATTACHEDIMAGE_POST_PERSIST = 'rkreferencemodule.attachedimage_post_persist';
    
    /**
     * The rkreferencemodule.attachedimage_pre_remove event is thrown before an existing attached image
     * is removed from the system.
     *
     * The event listener receives an
     * RK\ReferenceModule\Event\FilterAttachedImageEvent instance.
     *
     * @see RK\ReferenceModule\Listener\EntityLifecycleListener::preRemove()
     * @var string
     */
    const ATTACHEDIMAGE_PRE_REMOVE = 'rkreferencemodule.attachedimage_pre_remove';
    
    /**
     * The rkreferencemodule.attachedimage_post_remove event is thrown after an existing attached image
     * has been removed from the system.
     *
     * The event listener receives an
     * RK\ReferenceModule\Event\FilterAttachedImageEvent instance.
     *
     * @see RK\ReferenceModule\Listener\EntityLifecycleListener::postRemove()
     * @var string
     */
    const ATTACHEDIMAGE_POST_REMOVE = 'rkreferencemodule.attachedimage_post_remove';
    
    /**
     * The rkreferencemodule.attachedimage_pre_update event is thrown before an existing attached image
     * is updated in the system.
     *
     * The event listener receives an
     * RK\ReferenceModule\Event\FilterAttachedImageEvent instance.
     *
     * @see RK\ReferenceModule\Listener\EntityLifecycleListener::preUpdate()
     * @var string
     */
    const ATTACHEDIMAGE_PRE_UPDATE = 'rkreferencemodule.attachedimage_pre_update';
    
    /**
     * The rkreferencemodule.attachedimage_post_update event is thrown after an existing new attached image
     * has been updated in the system.
     *
     * The event listener receives an
     * RK\ReferenceModule\Event\FilterAttachedImageEvent instance.
     *
     * @see RK\ReferenceModule\Listener\EntityLifecycleListener::postUpdate()
     * @var string
     */
    const ATTACHEDIMAGE_POST_UPDATE = 'rkreferencemodule.attachedimage_post_update';
    
    /**
     * The rkreferencemodule.activity_post_load event is thrown when activities
     * are loaded from the database.
     *
     * The event listener receives an
     * RK\ReferenceModule\Event\FilterActivityEvent instance.
     *
     * @see RK\ReferenceModule\Listener\EntityLifecycleListener::postLoad()
     * @var string
     */
    const ACTIVITY_POST_LOAD = 'rkreferencemodule.activity_post_load';
    
    /**
     * The rkreferencemodule.activity_pre_persist event is thrown before a new activity
     * is created in the system.
     *
     * The event listener receives an
     * RK\ReferenceModule\Event\FilterActivityEvent instance.
     *
     * @see RK\ReferenceModule\Listener\EntityLifecycleListener::prePersist()
     * @var string
     */
    const ACTIVITY_PRE_PERSIST = 'rkreferencemodule.activity_pre_persist';
    
    /**
     * The rkreferencemodule.activity_post_persist event is thrown after a new activity
     * has been created in the system.
     *
     * The event listener receives an
     * RK\ReferenceModule\Event\FilterActivityEvent instance.
     *
     * @see RK\ReferenceModule\Listener\EntityLifecycleListener::postPersist()
     * @var string
     */
    const ACTIVITY_POST_PERSIST = 'rkreferencemodule.activity_post_persist';
    
    /**
     * The rkreferencemodule.activity_pre_remove event is thrown before an existing activity
     * is removed from the system.
     *
     * The event listener receives an
     * RK\ReferenceModule\Event\FilterActivityEvent instance.
     *
     * @see RK\ReferenceModule\Listener\EntityLifecycleListener::preRemove()
     * @var string
     */
    const ACTIVITY_PRE_REMOVE = 'rkreferencemodule.activity_pre_remove';
    
    /**
     * The rkreferencemodule.activity_post_remove event is thrown after an existing activity
     * has been removed from the system.
     *
     * The event listener receives an
     * RK\ReferenceModule\Event\FilterActivityEvent instance.
     *
     * @see RK\ReferenceModule\Listener\EntityLifecycleListener::postRemove()
     * @var string
     */
    const ACTIVITY_POST_REMOVE = 'rkreferencemodule.activity_post_remove';
    
    /**
     * The rkreferencemodule.activity_pre_update event is thrown before an existing activity
     * is updated in the system.
     *
     * The event listener receives an
     * RK\ReferenceModule\Event\FilterActivityEvent instance.
     *
     * @see RK\ReferenceModule\Listener\EntityLifecycleListener::preUpdate()
     * @var string
     */
    const ACTIVITY_PRE_UPDATE = 'rkreferencemodule.activity_pre_update';
    
    /**
     * The rkreferencemodule.activity_post_update event is thrown after an existing new activity
     * has been updated in the system.
     *
     * The event listener receives an
     * RK\ReferenceModule\Event\FilterActivityEvent instance.
     *
     * @see RK\ReferenceModule\Listener\EntityLifecycleListener::postUpdate()
     * @var string
     */
    const ACTIVITY_POST_UPDATE = 'rkreferencemodule.activity_post_update';
    
}
