<?php
/**
 * Reference.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\ReferenceModule\Base;

use Doctrine\DBAL\Connection;
use RuntimeException;
use Zikula\Core\AbstractExtensionInstaller;
use Zikula_Workflow_Util;

/**
 * Installer base class.
 */
abstract class AbstractReferenceModuleInstaller extends AbstractExtensionInstaller
{
    /**
     * Install the RKReferenceModule application.
     *
     * @return boolean True on success, or false
     *
     * @throws RuntimeException Thrown if database tables can not be created or another error occurs
     */
    public function install()
    {
        $logger = $this->container->get('logger');
        $userName = $this->container->get('zikula_users_module.current_user')->get('uname');
    
        // Check if upload directories exist and if needed create them
        try {
            $container = $this->container;
            $uploadHelper = new \RK\ReferenceModule\Helper\UploadHelper($container->get('translator.default'), $container->get('session'), $container->get('logger'), $container->get('zikula_users_module.current_user'), $container->get('zikula_extensions_module.api.variable'), $container->getParameter('datadir'));
            $uploadHelper->checkAndCreateAllUploadFolders();
        } catch (\Exception $e) {
            $this->addFlash('error', $e->getMessage());
            $logger->error('{app}: User {user} could not create upload folders during installation. Error details: {errorMessage}.', ['app' => 'RKReferenceModule', 'user' => $userName, 'errorMessage' => $e->getMessage()]);
        
            return false;
        }
        // create all tables from according entity definitions
        try {
            $this->schemaTool->create($this->listEntityClasses());
        } catch (\Exception $e) {
            $this->addFlash('error', $this->__('Doctrine Exception') . ': ' . $e->getMessage());
            $logger->error('{app}: Could not create the database tables during installation. Error details: {errorMessage}.', ['app' => 'RKReferenceModule', 'errorMessage' => $e->getMessage()]);
    
            return false;
        }
    
        // set up all our vars with initial values
        $this->setVar('attachedImageEntriesPerPage', '10');
        $this->setVar('linkOwnAttachedImagesOnAccountPage', true);
        $this->setVar('activityEntriesPerPage', '10');
        $this->setVar('linkOwnActivitiesOnAccountPage', true);
        $this->setVar('enableShrinkingForAttachedImageAddedImage', false);
        $this->setVar('shrinkWidthAttachedImageAddedImage', '800');
        $this->setVar('shrinkHeightAttachedImageAddedImage', '600');
        $this->setVar('thumbnailModeAttachedImageAddedImage',  'inset' );
        $this->setVar('thumbnailWidthAttachedImageAddedImageView', '32');
        $this->setVar('thumbnailHeightAttachedImageAddedImageView', '24');
        $this->setVar('thumbnailWidthAttachedImageAddedImageDisplay', '240');
        $this->setVar('thumbnailHeightAttachedImageAddedImageDisplay', '180');
        $this->setVar('thumbnailWidthAttachedImageAddedImageEdit', '240');
        $this->setVar('thumbnailHeightAttachedImageAddedImageEdit', '180');
        $this->setVar('enableShrinkingForActivityTitleImage', false);
        $this->setVar('shrinkWidthActivityTitleImage', '800');
        $this->setVar('shrinkHeightActivityTitleImage', '600');
        $this->setVar('thumbnailModeActivityTitleImage',  'inset' );
        $this->setVar('thumbnailWidthActivityTitleImageView', '32');
        $this->setVar('thumbnailHeightActivityTitleImageView', '24');
        $this->setVar('thumbnailWidthActivityTitleImageDisplay', '240');
        $this->setVar('thumbnailHeightActivityTitleImageDisplay', '180');
        $this->setVar('thumbnailWidthActivityTitleImageEdit', '240');
        $this->setVar('thumbnailHeightActivityTitleImageEdit', '180');
        $this->setVar('enableShrinkingForActivityReferenceImage', false);
        $this->setVar('shrinkWidthActivityReferenceImage', '800');
        $this->setVar('shrinkHeightActivityReferenceImage', '600');
        $this->setVar('thumbnailModeActivityReferenceImage',  'inset' );
        $this->setVar('thumbnailWidthActivityReferenceImageView', '32');
        $this->setVar('thumbnailHeightActivityReferenceImageView', '24');
        $this->setVar('thumbnailWidthActivityReferenceImageDisplay', '240');
        $this->setVar('thumbnailHeightActivityReferenceImageDisplay', '180');
        $this->setVar('thumbnailWidthActivityReferenceImageEdit', '240');
        $this->setVar('thumbnailHeightActivityReferenceImageEdit', '180');
    
        // create the default data
        $this->createDefaultData();
    
        // install subscriber hooks
        $this->hookApi->installSubscriberHooks($this->bundle->getMetaData());
        
    
        // initialisation successful
        return true;
    }
    
    /**
     * Upgrade the RKReferenceModule application from an older version.
     *
     * If the upgrade fails at some point, it returns the last upgraded version.
     *
     * @param integer $oldVersion Version to upgrade from
     *
     * @return boolean True on success, false otherwise
     *
     * @throws RuntimeException Thrown if database tables can not be updated
     */
    public function upgrade($oldVersion)
    {
    /*
        $logger = $this->container->get('logger');
    
        // Upgrade dependent on old version number
        switch ($oldVersion) {
            case '1.0.0':
                // do something
                // ...
                // update the database schema
                try {
                    $this->schemaTool->update($this->listEntityClasses());
                } catch (\Exception $e) {
                    $this->addFlash('error', $this->__('Doctrine Exception') . ': ' . $e->getMessage());
                    $logger->error('{app}: Could not update the database tables during the upgrade. Error details: {errorMessage}.', ['app' => 'RKReferenceModule', 'errorMessage' => $e->getMessage()]);
    
                    return false;
                }
        }
    
        // Note there are several helpers available for making migrating your extension from Zikula 1.3 to 1.4 easier.
        // The following convenience methods are each responsible for a single aspect of upgrading to Zikula 1.4.x.
    
        // here is a possible usage example
        // of course 1.2.3 should match the number you used for the last stable 1.3.x module version.
        /* if ($oldVersion = '1.2.3') {
            // rename module for all modvars
            $this->updateModVarsTo14();
            
            // update extension information about this app
            $this->updateExtensionInfoFor14();
            
            // rename existing permission rules
            $this->renamePermissionsFor14();
            
            // rename all tables
            $this->renameTablesFor14();
            
            // remove event handler definitions from database
            $this->dropEventHandlersFromDatabase();
            
            // update module name in the hook tables
            $this->updateHookNamesFor14();
            
            // update module name in the workflows table
            $this->updateWorkflowsFor14();
        } * /
    */
    
        // update successful
        return true;
    }
    
    /**
     * Renames the module name for variables in the module_vars table.
     */
    protected function updateModVarsTo14()
    {
        $dbName = $this->getDbName();
        $conn = $this->getConnection();
    
        $conn->executeQuery("
            UPDATE $dbName.module_vars
            SET modname = 'RKReferenceModule'
            WHERE modname = 'Reference';
        ");
    }
    
    /**
     * Renames this application in the core's extensions table.
     */
    protected function updateExtensionInfoFor14()
    {
        $conn = $this->getConnection();
        $dbName = $this->getDbName();
    
        $conn->executeQuery("
            UPDATE $dbName.modules
            SET name = 'RKReferenceModule',
                directory = 'RK/ReferenceModule'
            WHERE name = 'Reference';
        ");
    }
    
    /**
     * Renames all permission rules stored for this app.
     */
    protected function renamePermissionsFor14()
    {
        $conn = $this->getConnection();
        $dbName = $this->getDbName();
    
        $componentLength = strlen('Reference') + 1;
    
        $conn->executeQuery("
            UPDATE $dbName.group_perms
            SET component = CONCAT('RKReferenceModule', SUBSTRING(component, $componentLength))
            WHERE component LIKE 'Reference%';
        ");
    }
    
    /**
     * Renames all (existing) tables of this app.
     */
    protected function renameTablesFor14()
    {
        $conn = $this->getConnection();
        $dbName = $this->getDbName();
    
        $oldPrefix = 'refere_';
        $oldPrefixLength = strlen($oldPrefix);
        $newPrefix = 'rk_refere_';
    
        $sm = $conn->getSchemaManager();
        $tables = $sm->listTables();
        foreach ($tables as $table) {
            $tableName = $table->getName();
            if (substr($tableName, 0, $oldPrefixLength) != $oldPrefix) {
                continue;
            }
    
            $newTableName = str_replace($oldPrefix, $newPrefix, $tableName);
    
            $conn->executeQuery("
                RENAME TABLE $dbName.$tableName
                TO $dbName.$newTableName;
            ");
        }
    }
    
    /**
     * Removes event handlers from database as they are now described by service definitions and managed by dependency injection.
     */
    protected function dropEventHandlersFromDatabase()
    {
        \EventUtil::unregisterPersistentModuleHandlers('Reference');
    }
    
    /**
     * Updates the module name in the hook tables.
     */
    protected function updateHookNamesFor14()
    {
        $conn = $this->getConnection();
        $dbName = $this->getDbName();
    
        $conn->executeQuery("
            UPDATE $dbName.hook_area
            SET owner = 'RKReferenceModule'
            WHERE owner = 'Reference';
        ");
    
        $componentLength = strlen('subscriber.reference') + 1;
        $conn->executeQuery("
            UPDATE $dbName.hook_area
            SET areaname = CONCAT('subscriber.rkreferencemodule', SUBSTRING(areaname, $componentLength))
            WHERE areaname LIKE 'subscriber.reference%';
        ");
    
        $conn->executeQuery("
            UPDATE $dbName.hook_binding
            SET sowner = 'RKReferenceModule'
            WHERE sowner = 'Reference';
        ");
    
        $conn->executeQuery("
            UPDATE $dbName.hook_runtime
            SET sowner = 'RKReferenceModule'
            WHERE sowner = 'Reference';
        ");
    
        $componentLength = strlen('reference') + 1;
        $conn->executeQuery("
            UPDATE $dbName.hook_runtime
            SET eventname = CONCAT('rkreferencemodule', SUBSTRING(eventname, $componentLength))
            WHERE eventname LIKE 'reference%';
        ");
    
        $conn->executeQuery("
            UPDATE $dbName.hook_subscriber
            SET owner = 'RKReferenceModule'
            WHERE owner = 'Reference';
        ");
    
        $componentLength = strlen('reference') + 1;
        $conn->executeQuery("
            UPDATE $dbName.hook_subscriber
            SET eventname = CONCAT('rkreferencemodule', SUBSTRING(eventname, $componentLength))
            WHERE eventname LIKE 'reference%';
        ");
    }
    
    /**
     * Updates the module name in the workflows table.
     */
    protected function updateWorkflowsFor14()
    {
        $conn = $this->getConnection();
        $dbName = $this->getDbName();
    
        $conn->executeQuery("
            UPDATE $dbName.workflows
            SET module = 'RKReferenceModule'
            WHERE module = 'Reference';
        ");
    }
    
    /**
     * Returns connection to the database.
     *
     * @return Connection the current connection
     */
    protected function getConnection()
    {
        $entityManager = $this->container->get('doctrine.orm.default_entity_manager');
        $connection = $entityManager->getConnection();
    
        return $connection;
    }
    
    /**
     * Returns the name of the default system database.
     *
     * @return string the database name
     */
    protected function getDbName()
    {
        return $this->container->getParameter('database_name');
    }
    
    /**
     * Uninstall RKReferenceModule.
     *
     * @return boolean True on success, false otherwise
     *
     * @throws RuntimeException Thrown if database tables or stored workflows can not be removed
     */
    public function uninstall()
    {
        $logger = $this->container->get('logger');
    
        // delete stored object workflows
        $result = Zikula_Workflow_Util::deleteWorkflowsForModule('RKReferenceModule');
        if (false === $result) {
            $this->addFlash('error', $this->__f('An error was encountered while removing stored object workflows for the %extension% extension.', ['%extension%' => 'RKReferenceModule']));
            $logger->error('{app}: Could not remove stored object workflows during uninstallation.', ['app' => 'RKReferenceModule']);
    
            return false;
        }
    
        try {
            $this->schemaTool->drop($this->listEntityClasses());
        } catch (\Exception $e) {
            $this->addFlash('error', $this->__('Doctrine Exception') . ': ' . $e->getMessage());
            $logger->error('{app}: Could not remove the database tables during uninstallation. Error details: {errorMessage}.', ['app' => 'RKReferenceModule', 'errorMessage' => $e->getMessage()]);
    
            return false;
        }
    
        // uninstall subscriber hooks
        $this->hookApi->uninstallSubscriberHooks($this->bundle->getMetaData());
        
    
        // remove all module vars
        $this->delVars();
    
        // remove all thumbnails
        $manager = $this->container->get('systemplugin.imagine.manager');
        $manager->setModule('RKReferenceModule');
        $manager->cleanupModuleThumbs();
    
        // remind user about upload folders not being deleted
        $uploadPath = $this->container->getParameter('datadir') . '/RKReferenceModule/';
        $this->addFlash('status', $this->__f('The upload directories at "%path%" can be removed manually.', ['%path%' => $uploadPath]));
    
        // uninstallation successful
        return true;
    }
    
    /**
     * Build array with all entity classes for RKReferenceModule.
     *
     * @return array list of class names
     */
    protected function listEntityClasses()
    {
        $classNames = [];
        $classNames[] = 'RK\ReferenceModule\Entity\AttachedImageEntity';
        $classNames[] = 'RK\ReferenceModule\Entity\ActivityEntity';
    
        return $classNames;
    }
    
    /**
     * Create the default data for RKReferenceModule.
     *
     * @return void
     */
    protected function createDefaultData()
    {
        $entityManager = $this->container->get('doctrine.orm.default_entity_manager');
        $logger = $this->container->get('logger');
        $request = $this->container->get('request_stack')->getCurrentRequest();
        
        $entityClass = 'RK\ReferenceModule\Entity\AttachedImageEntity';
        $entityManager->getRepository($entityClass)->truncateTable($logger);
        $entityClass = 'RK\ReferenceModule\Entity\ActivityEntity';
        $entityManager->getRepository($entityClass)->truncateTable($logger);
    }
}
