<?php
/**
 * Reference.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\ReferenceModule\Form\Type\QuickNavigation;

use RK\ReferenceModule\Form\Type\QuickNavigation\Base\AbstractAttachedImageQuickNavType;

/**
 * Attached image quick navigation form type implementation class.
 */
class AttachedImageQuickNavType extends AbstractAttachedImageQuickNavType
{
    // feel free to extend the base form type class here
}
