<?php
/**
 * Info.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.1 (http://modulestudio.de).
 */

namespace RK\InfoModule\Form\Plugin;

use RK\InfoModule\Form\Plugin\Base\AbstractItemSelector;

/**
 * Item selector plugin implementation class.
 */
class ItemSelector extends AbstractItemSelector
{
    // feel free to add your customisation here
}
