<?php
/**
 * Info.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\InfoModule\Event;

use RK\InfoModule\Event\Base\AbstractFilterInformationEvent;

/**
 * Event implementation class for filtering information processing.
 */
class FilterInformationEvent extends AbstractFilterInformationEvent
{
    // feel free to extend the event class here
}
