<?php
/**
 * Info.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\InfoModule\Entity;

use RK\InfoModule\Entity\Base\AbstractInformationTranslationEntity as BaseEntity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Entity extension domain class storing information translations.
 *
 * This is the concrete translation class for information entities.
 *
 * @ORM\Entity(repositoryClass="RK\InfoModule\Entity\Repository\InformationTranslationRepository")
 * @ORM\Table(name="rk_info_information_translation",
 *     indexes={
 *         @ORM\Index(name="translations_lookup_idx", columns={
 *             "locale", "object_class", "foreign_key"
 *         })
 *     }
 * )
 */
class InformationTranslationEntity extends BaseEntity
{
    // feel free to add your own methods here
}
