<?php
/**
 * Info.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\InfoModule\Entity;

use RK\InfoModule\Entity\Base\AbstractInformationEntity as BaseEntity;

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Gedmo\Translatable\Translatable;
use Symfony\Component\Validator\Constraints as Assert;
use RK\InfoModule\Traits\EntityWorkflowTrait;
use RK\InfoModule\Traits\StandardFieldsTrait;

/**
 * Entity class that defines the entity structure and behaviours.
 *
 * This is the concrete entity class for information entities.
  * @Gedmo\TranslationEntity(class="RK\InfoModule\Entity\InformationTranslationEntity")
 * @ORM\Entity(repositoryClass="RK\InfoModule\Entity\Repository\InformationRepository")
 * @ORM\Table(name="rk_info_information",
 *     indexes={
 *         @ORM\Index(name="workflowstateindex", columns={"workflowState"})
 *     }
 * )
 */
class InformationEntity extends BaseEntity
{
    // feel free to add your own methods here
}
