<?php
/**
 * Info.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.1 (http://modulestudio.de).
 */

namespace RK\InfoModule;

use RK\InfoModule\Base\AbstractInfoModuleInstaller;

/**
 * Installer implementation class.
 */
class InfoModuleInstaller extends AbstractInfoModuleInstaller
{
    // feel free to extend the installer here
}
