<?php
/**
 * Info.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\InfoModule;

use RK\InfoModule\Base\AbstractInfoEvents;

/**
 * Events definition implementation class.
 */
class InfoEvents extends AbstractInfoEvents
{
    // feel free to extend the events definition here
}
