<?php
/**
 * Reference.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\ReferenceModule\Form\Type;

use RK\ReferenceModule\Form\Type\Base\AbstractAttachedImageType;

/**
 * Attached image editing form type implementation class.
 */
class AttachedImageType extends AbstractAttachedImageType
{
    // feel free to extend the attached image editing form type class here
}
