<?php
/**
 * Reference.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\ReferenceModule\Form\Type;

use RK\ReferenceModule\Form\Type\Base\AbstractActivityType;

/**
 * Activity editing form type implementation class.
 */
class ActivityType extends AbstractActivityType
{
    // feel free to extend the activity editing form type class here
}
