<?php
/**
 * Reference.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\ReferenceModule\Event\Base;

use Symfony\Component\EventDispatcher\Event;
use RK\ReferenceModule\Entity\ActivityEntity;

/**
 * Event base class for filtering activity processing.
 */
class AbstractFilterActivityEvent extends Event
{
    /**
     * @var ActivityEntity Reference to treated entity instance.
     */
    protected $activity;

    public function __construct(ActivityEntity $activity)
    {
        $this->activity = $activity;
    }

    public function getActivity()
    {
        return $this->activity;
    }
}
