<?php
/**
 * Reference.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\ReferenceModule\Event\Base;

use Symfony\Component\EventDispatcher\Event;
use RK\ReferenceModule\Entity\AttachedImageEntity;

/**
 * Event base class for filtering attached image processing.
 */
class AbstractFilterAttachedImageEvent extends Event
{
    /**
     * @var AttachedImageEntity Reference to treated entity instance.
     */
    protected $attachedImage;

    public function __construct(AttachedImageEntity $attachedImage)
    {
        $this->attachedImage = $attachedImage;
    }

    public function getAttachedImage()
    {
        return $this->attachedImage;
    }
}
