<?php
/**
 * Info.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\InfoModule\Entity\Base;

use Gedmo\Translatable\Entity\MappedSuperclass\AbstractTranslation;

/**
 * Entity extension domain class storing information translations.
 *
 * This is the base translation class for information entities.
 */
abstract class AbstractInformationTranslationEntity extends AbstractTranslation
{
}
