<?php
/**
 * Info.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.1 (http://modulestudio.de).
 */

namespace RK\InfoModule\Form\Type\Base;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Zikula\Common\Translator\TranslatorInterface;
use Zikula\Common\Translator\TranslatorTrait;
use Zikula\ExtensionsModule\Api\VariableApi;
use RK\InfoModule\Entity\Factory\InfoFactory;
use RK\InfoModule\Helper\FeatureActivationHelper;
use RK\InfoModule\Helper\ListEntriesHelper;
use RK\InfoModule\Helper\TranslatableHelper;

/**
 * Information editing form type base class.
 */
abstract class AbstractInformationType extends AbstractType
{
    use TranslatorTrait;

    /**
     * @var InfoFactory
     */
    protected $entityFactory;

    /**
     * @var VariableApi
     */
    protected $variableApi;

    /**
     * @var TranslatableHelper
     */
    protected $translatableHelper;

    /**
     * @var ListEntriesHelper
     */
    protected $listHelper;

    /**
     * @var FeatureActivationHelper
     */
    protected $featureActivationHelper;

    /**
     * InformationType constructor.
     *
     * @param TranslatorInterface $translator     Translator service instance
     * @param InfoFactory        $entityFactory Entity factory service instance
     * @param VariableApi         $variableApi VariableApi service instance
     * @param TranslatableHelper  $translatableHelper TranslatableHelper service instance
     * @param ListEntriesHelper   $listHelper     ListEntriesHelper service instance
     * @param FeatureActivationHelper $featureActivationHelper FeatureActivationHelper service instance
     */
    public function __construct(TranslatorInterface $translator, InfoFactory $entityFactory, VariableApi $variableApi, TranslatableHelper $translatableHelper, ListEntriesHelper $listHelper, FeatureActivationHelper $featureActivationHelper)
    {
        $this->setTranslator($translator);
        $this->entityFactory = $entityFactory;
        $this->variableApi = $variableApi;
        $this->translatableHelper = $translatableHelper;
        $this->listHelper = $listHelper;
        $this->featureActivationHelper = $featureActivationHelper;
    }

    /**
     * Sets the translator.
     *
     * @param TranslatorInterface $translator Translator service instance
     */
    public function setTranslator(/*TranslatorInterface */$translator)
    {
        $this->translator = $translator;
    }

    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $this->addEntityFields($builder, $options);
        $this->addModerationFields($builder, $options);
        $this->addReturnControlField($builder, $options);
        $this->addSubmitButtons($builder, $options);
    }

    /**
     * Adds basic entity fields.
     *
     * @param FormBuilderInterface $builder The form builder
     * @param array                $options The options
     */
    public function addEntityFields(FormBuilderInterface $builder, array $options)
    {
        $useOnlyCurrentLanguage = true;
        if ($this->variableApi->getSystemVar('multilingual') && $this->featureActivationHelper->isEnabled(FeatureActivationHelper::TRANSLATIONS, 'information')) {
            $supportedLanguages = $this->translatableHelper->getSupportedLanguages('information');
            if (is_array($supportedLanguages) && count($supportedLanguages) > 1) {
                $useOnlyCurrentLanguage = false;
                $currentLanguage = $this->translatableHelper->getCurrentLanguage();
                foreach ($supportedLanguages as $language) {
                    if ($language != $currentLanguage) {
                        continue;
                    }
                    
                    $builder->add('title', 'Symfony\Component\Form\Extension\Core\Type\TextType', [
                        'label' => $this->__('Title') . ':',
                        'empty_data' => '',
                        'attr' => [
                            'maxlength' => 255,
                            'class' => '',
                            'title' => $this->__('Enter the title of the information')
                        ],'required' => true,
                    ]);
                    
                    $builder->add('theDescription', 'Symfony\Component\Form\Extension\Core\Type\TextareaType', [
                        'label' => $this->__('The description') . ':',
                        'empty_data' => '',
                        'attr' => [
                            'maxlength' => 8000,
                            'class' => '',
                            'title' => $this->__('Enter the the description of the information')
                        ],'required' => true
                    ]);
                }
                foreach ($supportedLanguages as $language) {
                    if ($language == $currentLanguage) {
                        continue;
                    }
                    
                    $builder->add('title' . $language, 'Symfony\Component\Form\Extension\Core\Type\TextType', [
                        'label' => $this->__('Title') . ':',
                        'empty_data' => '',
                        'mapped' => false,
                        'attr' => [
                            'maxlength' => 255,
                            'class' => '',
                            'title' => $this->__('Enter the title of the information')
                        ],'required' => true,
                    ]);
                    
                    $builder->add('theDescription' . $language, 'Symfony\Component\Form\Extension\Core\Type\TextareaType', [
                        'label' => $this->__('The description') . ':',
                        'empty_data' => '',
                        'mapped' => false,
                        'attr' => [
                            'maxlength' => 8000,
                            'class' => '',
                            'title' => $this->__('Enter the the description of the information')
                        ],'required' => true
                    ]);
                }
            }
        }
        if (true === $useOnlyCurrentLanguage) {
            $language = $this->translatableHelper->getCurrentLanguage();
            
            $builder->add('title', 'Symfony\Component\Form\Extension\Core\Type\TextType', [
                'label' => $this->__('Title') . ':',
                'empty_data' => '',
                'attr' => [
                    'maxlength' => 255,
                    'class' => '',
                    'title' => $this->__('Enter the title of the information')
                ],'required' => true,
            ]);
            
            $builder->add('theDescription', 'Symfony\Component\Form\Extension\Core\Type\TextareaType', [
                'label' => $this->__('The description') . ':',
                'empty_data' => '',
                'attr' => [
                    'maxlength' => 8000,
                    'class' => '',
                    'title' => $this->__('Enter the the description of the information')
                ],'required' => true
            ]);
        }
    }

    /**
     * Adds special fields for moderators.
     *
     * @param FormBuilderInterface $builder The form builder
     * @param array                $options The options
     */
    public function addModerationFields(FormBuilderInterface $builder, array $options)
    {
        if (!$options['hasModeratePermission']) {
            return;
        }
    
        $builder->add('moderationSpecificCreator', 'RK\InfoModule\Form\Type\Field\UserType', [
            'mapped' => false,
            'label' => $this->__('Creator') . ':',
            'attr' => [
                'maxlength' => 11,
                'class' => ' validate-digits',
                'title' => $this->__('Here you can choose a user which will be set as creator')
            ],
            'empty_data' => 0,
            'required' => false,
            'help' => $this->__('Here you can choose a user which will be set as creator')
        ]);
        $builder->add('moderationSpecificCreationDate', 'RK\InfoModule\Form\Type\Field\DateTimeType', [
            'mapped' => false,
            'label' => $this->__('Creation date') . ':',
            'attr' => [
                'class' => '',
                'title' => $this->__('Here you can choose a custom creation date')
            ],
            'empty_data' => '',
            'required' => false,
            'widget' => 'single_text',
            'help' => $this->__('Here you can choose a custom creation date')
        ]);
    }

    /**
     * Adds the return control field.
     *
     * @param FormBuilderInterface $builder The form builder
     * @param array                $options The options
     */
    public function addReturnControlField(FormBuilderInterface $builder, array $options)
    {
        if ($options['mode'] != 'create') {
            return;
        }
        $builder->add('repeatCreation', 'Symfony\Component\Form\Extension\Core\Type\CheckboxType', [
            'mapped' => false,
            'label' => $this->__('Create another item after save'),
            'required' => false
        ]);
    }

    /**
     * Adds submit buttons.
     *
     * @param FormBuilderInterface $builder The form builder
     * @param array                $options The options
     */
    public function addSubmitButtons(FormBuilderInterface $builder, array $options)
    {
        foreach ($options['actions'] as $action) {
            $builder->add($action['id'], 'Symfony\Component\Form\Extension\Core\Type\SubmitType', [
                'label' => $this->__(/** @Ignore */$action['title']),
                'icon' => ($action['id'] == 'delete' ? 'fa-trash-o' : ''),
                'attr' => [
                    'class' => $action['buttonClass'],
                    'title' => $this->__(/** @Ignore */$action['description'])
                ]
            ]);
        }
        $builder->add('reset', 'Symfony\Component\Form\Extension\Core\Type\ResetType', [
            'label' => $this->__('Reset'),
            'icon' => 'fa-refresh',
            'attr' => [
                'class' => 'btn btn-default',
                'formnovalidate' => 'formnovalidate'
            ]
        ]);
        $builder->add('cancel', 'Symfony\Component\Form\Extension\Core\Type\SubmitType', [
            'label' => $this->__('Cancel'),
            'icon' => 'fa-times',
            'attr' => [
                'class' => 'btn btn-default',
                'formnovalidate' => 'formnovalidate'
            ]
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'rkinfomodule_information';
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver
            ->setDefaults([
                // define class for underlying data (required for embedding forms)
                'data_class' => 'RK\InfoModule\Entity\InformationEntity',
                'empty_data' => function (FormInterface $form) {
                    return $this->entityFactory->createInformation();
                },
                'error_mapping' => [
                ],
                'mode' => 'create',
                'actions' => [],
                'hasModeratePermission' => false,
            ])
            ->setRequired(['mode', 'actions'])
            ->setAllowedTypes([
                'mode' => 'string',
                'actions' => 'array',
                'hasModeratePermission' => 'bool',
            ])
            ->setAllowedValues([
                'mode' => ['create', 'edit']
            ])
        ;
    }
}
