<?php
/**
 * Info.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\InfoModule\DependencyInjection;

use RK\InfoModule\DependencyInjection\Base\AbstractRKInfoExtension;

/**
 * Implementation class for service definition loader using the DependencyInjection extension.
 */
class RKInfoExtension extends AbstractRKInfoExtension
{
    // custom enhancements can go here
}
