<?php
/**
 * Info.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\InfoModule\Base;

/**
 * Events definition base class.
 */
abstract class AbstractInfoEvents
{
    /**
     * The rkinfomodule.information_post_load event is thrown when informations
     * are loaded from the database.
     *
     * The event listener receives an
     * RK\InfoModule\Event\FilterInformationEvent instance.
     *
     * @see RK\InfoModule\Listener\EntityLifecycleListener::postLoad()
     * @var string
     */
    const INFORMATION_POST_LOAD = 'rkinfomodule.information_post_load';
    
    /**
     * The rkinfomodule.information_pre_persist event is thrown before a new information
     * is created in the system.
     *
     * The event listener receives an
     * RK\InfoModule\Event\FilterInformationEvent instance.
     *
     * @see RK\InfoModule\Listener\EntityLifecycleListener::prePersist()
     * @var string
     */
    const INFORMATION_PRE_PERSIST = 'rkinfomodule.information_pre_persist';
    
    /**
     * The rkinfomodule.information_post_persist event is thrown after a new information
     * has been created in the system.
     *
     * The event listener receives an
     * RK\InfoModule\Event\FilterInformationEvent instance.
     *
     * @see RK\InfoModule\Listener\EntityLifecycleListener::postPersist()
     * @var string
     */
    const INFORMATION_POST_PERSIST = 'rkinfomodule.information_post_persist';
    
    /**
     * The rkinfomodule.information_pre_remove event is thrown before an existing information
     * is removed from the system.
     *
     * The event listener receives an
     * RK\InfoModule\Event\FilterInformationEvent instance.
     *
     * @see RK\InfoModule\Listener\EntityLifecycleListener::preRemove()
     * @var string
     */
    const INFORMATION_PRE_REMOVE = 'rkinfomodule.information_pre_remove';
    
    /**
     * The rkinfomodule.information_post_remove event is thrown after an existing information
     * has been removed from the system.
     *
     * The event listener receives an
     * RK\InfoModule\Event\FilterInformationEvent instance.
     *
     * @see RK\InfoModule\Listener\EntityLifecycleListener::postRemove()
     * @var string
     */
    const INFORMATION_POST_REMOVE = 'rkinfomodule.information_post_remove';
    
    /**
     * The rkinfomodule.information_pre_update event is thrown before an existing information
     * is updated in the system.
     *
     * The event listener receives an
     * RK\InfoModule\Event\FilterInformationEvent instance.
     *
     * @see RK\InfoModule\Listener\EntityLifecycleListener::preUpdate()
     * @var string
     */
    const INFORMATION_PRE_UPDATE = 'rkinfomodule.information_pre_update';
    
    /**
     * The rkinfomodule.information_post_update event is thrown after an existing new information
     * has been updated in the system.
     *
     * The event listener receives an
     * RK\InfoModule\Event\FilterInformationEvent instance.
     *
     * @see RK\InfoModule\Listener\EntityLifecycleListener::postUpdate()
     * @var string
     */
    const INFORMATION_POST_UPDATE = 'rkinfomodule.information_post_update';
    
}
