<?php
/**
 * Reference.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\ReferenceModule\Form\Type\Base;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Zikula\Common\Translator\TranslatorInterface;
use Zikula\Common\Translator\TranslatorTrait;
use Zikula\SettingsModule\Api\LocaleApi;
use RK\ReferenceModule\Entity\Factory\ReferenceFactory;
use RK\ReferenceModule\Helper\ListEntriesHelper;

/**
 * Activity editing form type base class.
 */
abstract class AbstractActivityType extends AbstractType
{
    use TranslatorTrait;

    /**
     * @var ReferenceFactory
     */
    protected $entityFactory;

    /**
     * @var ListEntriesHelper
     */
    protected $listHelper;

    /**
     * @var LocaleApi
     */
    protected $localeApi;

    /**
     * ActivityType constructor.
     *
     * @param TranslatorInterface $translator    Translator service instance
     * @param ReferenceFactory        $entityFactory Entity factory service instance
     * @param ListEntriesHelper   $listHelper    ListEntriesHelper service instance
     * @param LocaleApi           $localeApi     LocaleApi service instance
     */
    public function __construct(TranslatorInterface $translator, ReferenceFactory $entityFactory, ListEntriesHelper $listHelper, LocaleApi $localeApi)
    {
        $this->setTranslator($translator);
        $this->entityFactory = $entityFactory;
        $this->listHelper = $listHelper;
        $this->localeApi = $localeApi;
    }

    /**
     * Sets the translator.
     *
     * @param TranslatorInterface $translator Translator service instance
     */
    public function setTranslator(/*TranslatorInterface */$translator)
    {
        $this->translator = $translator;
    }

    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $this->addEntityFields($builder, $options);
        $this->addIncomingRelationshipFields($builder, $options);
        $this->addModerationFields($builder, $options);
        $this->addReturnControlField($builder, $options);
        $this->addSubmitButtons($builder, $options);

        $builder->addEventListener(FormEvents::PRE_SET_DATA, function (FormEvent $event) {
            $entity = $event->getData();
            foreach (['titleImage', 'referenceImage'] as $uploadFieldName) {
                $entity[$uploadFieldName] = [
                    $uploadFieldName => $entity[$uploadFieldName] instanceof File ? $entity[$uploadFieldName]->getPathname() : null
                ];
            }
        });
        $builder->addEventListener(FormEvents::SUBMIT, function (FormEvent $event) {
            $entity = $event->getData();
            foreach (['titleImage', 'referenceImage'] as $uploadFieldName) {
                if (is_array($entity[$uploadFieldName])) {
                    $entity[$uploadFieldName] = $entity[$uploadFieldName][$uploadFieldName];
                }
            }
        });
    }

    /**
     * Adds basic entity fields.
     *
     * @param FormBuilderInterface $builder The form builder
     * @param array                $options The options
     */
    public function addEntityFields(FormBuilderInterface $builder, array $options)
    {
        
        $builder->add('displayLanguage', 'Zikula\Bundle\FormExtensionBundle\Form\Type\LocaleType', [
            'label' => $this->__('Display language') . ':',
            'label_attr' => [
                'class' => 'tooltips',
                'title' => $this->__('Select in which language the activity should be shown. Select "all" for every language.')
            ],
            'help' => $this->__('Select in which language the activity should be shown. Select "all" for every language.'),
            'empty_data' => '',
            'attr' => [
                'maxlength' => 255,
                'class' => ' validate-nospace',
                'title' => $this->__('Choose the display language of the activity')
            ],
            'required' => false
            ,'placeholder' => $this->__('All'),
            'choices' => $this->localeApi->getSupportedLocaleNames(),
            'choices_as_values' => true
        ]);
        
        $builder->add('title', 'Symfony\Component\Form\Extension\Core\Type\TextType', [
            'label' => $this->__('Title') . ':',
            'label_attr' => [
                'class' => 'tooltips',
                'title' => $this->__('This is the title of your activity.')
            ],
            'help' => $this->__('This is the title of your activity.'),
            'empty_data' => '',
            'attr' => [
                'maxlength' => 255,
                'class' => '',
                'title' => $this->__('Enter the title of the activity')
            ],
            'required' => true
            ,
        ]);
        
        $builder->add('titleImage', 'RK\ReferenceModule\Form\Type\Field\UploadType', [
            'label' => $this->__('Title image') . ':',
            'label_attr' => [
                'class' => 'tooltips',
                'title' => $this->__('The image should have a ratio of 3:1. The width should be not less than 1200px. The title image will be used at the top of the activity page.')
            ],
            'help' => $this->__('The image should have a ratio of 3:1. The width should be not less than 1200px. The title image will be used at the top of the activity page.'),
            'attr' => [
                'class' => ' validate-upload',
                'title' => $this->__('Enter the title image of the activity')
            ],
            'required' => true && $options['mode'] == 'create'
            ,'entity' => $options['entity'],
            'allowed_extensions' => 'gif, jpeg, jpg, png',
            'allowed_size' => ''
        ]);
        
        $builder->add('copyrightTitleImage', 'Symfony\Component\Form\Extension\Core\Type\TextType', [
            'label' => $this->__('Copyright title image') . ':',
            'empty_data' => '',
            'attr' => [
                'maxlength' => 255,
                'class' => '',
                'title' => $this->__('Enter the copyright title image of the activity')
            ],
            'required' => false
            ,
        ]);
        
        $builder->add('referenceImage', 'RK\ReferenceModule\Form\Type\Field\UploadType', [
            'label' => $this->__('Reference image') . ':',
            'label_attr' => [
                'class' => 'tooltips',
                'title' => $this->__('This image is the reference of the activity.')
            ],
            'help' => $this->__('This image is the reference of the activity.'),
            'attr' => [
                'class' => ' validate-upload',
                'title' => $this->__('Enter the reference image of the activity')
            ],
            'required' => false && $options['mode'] == 'create'
            ,'entity' => $options['entity'],
            'allowed_extensions' => 'gif, jpeg, jpg, png',
            'allowed_size' => ''
        ]);
        
        $builder->add('copyrightReferenceImage', 'Symfony\Component\Form\Extension\Core\Type\TextType', [
            'label' => $this->__('Copyright reference image') . ':',
            'empty_data' => '',
            'attr' => [
                'maxlength' => 255,
                'class' => '',
                'title' => $this->__('Enter the copyright reference image of the activity')
            ],
            'required' => false
            ,
        ]);
        
        $builder->add('teaserDescription', 'Symfony\Component\Form\Extension\Core\Type\TextareaType', [
            'label' => $this->__('Teaser description') . ':',
            'label_attr' => [
                'class' => 'tooltips',
                'title' => $this->__('this description will be shown in the overview')
            ],
            'help' => $this->__('this description will be shown in the overview'),
            'empty_data' => '',
            'attr' => [
                'maxlength' => 500,
                'class' => '',
                'title' => $this->__('Enter the teaser description of the activity')
            ],
            'required' => true
            ,
        ]);
        
        $builder->add('activityDescription', 'Symfony\Component\Form\Extension\Core\Type\TextareaType', [
            'label' => $this->__('Activity description') . ':',
            'empty_data' => '',
            'attr' => [
                'maxlength' => 5000,
                'class' => '',
                'title' => $this->__('Enter the activity description of the activity')
            ],
            'required' => false
            ,
        ]);
        
        $builder->add('infoField1', 'Symfony\Component\Form\Extension\Core\Type\TextType', [
            'label' => $this->__('Info field 1') . ':',
            'label_attr' => [
                'class' => 'tooltips',
                'title' => $this->__('You can use the infofields to display some special infos like the year of creation or the specific NC brand or whatever fits to the activity. The info field 1 will appear also inside the headline. All other info fields will not.')
            ],
            'help' => $this->__('You can use the infofields to display some special infos like the year of creation or the specific NC brand or whatever fits to the activity. The info field 1 will appear also inside the headline. All other info fields will not.'),
            'empty_data' => '',
            'attr' => [
                'maxlength' => 255,
                'class' => '',
                'title' => $this->__('Enter the info field 1 of the activity')
            ],
            'required' => false
            ,
        ]);
        
        $builder->add('infoField2', 'Symfony\Component\Form\Extension\Core\Type\TextType', [
            'label' => $this->__('Info field 2') . ':',
            'empty_data' => '',
            'attr' => [
                'maxlength' => 255,
                'class' => '',
                'title' => $this->__('Enter the info field 2 of the activity')
            ],
            'required' => false
            ,
        ]);
        
        $builder->add('infoField3', 'Symfony\Component\Form\Extension\Core\Type\TextType', [
            'label' => $this->__('Info field 3') . ':',
            'empty_data' => '',
            'attr' => [
                'maxlength' => 255,
                'class' => '',
                'title' => $this->__('Enter the info field 3 of the activity')
            ],
            'required' => false
            ,
        ]);
        
        $builder->add('infoField4', 'Symfony\Component\Form\Extension\Core\Type\TextType', [
            'label' => $this->__('Info field 4') . ':',
            'empty_data' => '',
            'attr' => [
                'maxlength' => 255,
                'class' => '',
                'title' => $this->__('Enter the info field 4 of the activity')
            ],
            'required' => false
            ,
        ]);
        
        $builder->add('infoField5', 'Symfony\Component\Form\Extension\Core\Type\TextType', [
            'label' => $this->__('Info field 5') . ':',
            'empty_data' => '',
            'attr' => [
                'maxlength' => 255,
                'class' => '',
                'title' => $this->__('Enter the info field 5 of the activity')
            ],
            'required' => false
            ,
        ]);
    }

    /**
     * Adds fields for incoming relationships.
     *
     * @param FormBuilderInterface $builder The form builder
     * @param array                $options The options
     */
    public function addIncomingRelationshipFields(FormBuilderInterface $builder, array $options)
    {
        $queryBuilder = function(EntityRepository $er) {
            // select without joins
            return $er->getListQueryBuilder('', '', false);
        };
        $builder->add('activity', 'Symfony\Bridge\Doctrine\Form\Type\EntityType', [
            'class' => 'RKReferenceModule:AttachedImageEntity',
            'choice_label' => 'getTitleFromDisplayPattern',
            'multiple' => false,
            'expanded' => false,
            'query_builder' => $queryBuilder,
            'label' => $this->__('Activity'),
            'attr' => [
                'title' => $this->__('Choose the activity')
            ]
        ]);
    }

    /**
     * Adds special fields for moderators.
     *
     * @param FormBuilderInterface $builder The form builder
     * @param array                $options The options
     */
    public function addModerationFields(FormBuilderInterface $builder, array $options)
    {
        if (!$options['has_moderate_permission']) {
            return;
        }
    
        $builder->add('moderationSpecificCreator', 'RK\ReferenceModule\Form\Type\Field\UserType', [
            'mapped' => false,
            'label' => $this->__('Creator') . ':',
            'attr' => [
                'maxlength' => 11,
                'class' => ' validate-digits',
                'title' => $this->__('Here you can choose a user which will be set as creator')
            ],
            'empty_data' => 0,
            'required' => false,
            'help' => $this->__('Here you can choose a user which will be set as creator')
        ]);
        $builder->add('moderationSpecificCreationDate', 'RK\ReferenceModule\Form\Type\Field\DateTimeType', [
            'mapped' => false,
            'label' => $this->__('Creation date') . ':',
            'attr' => [
                'class' => '',
                'title' => $this->__('Here you can choose a custom creation date')
            ],
            'empty_data' => '',
            'required' => false,
            'widget' => 'single_text',
            'help' => $this->__('Here you can choose a custom creation date')
        ]);
    }

    /**
     * Adds the return control field.
     *
     * @param FormBuilderInterface $builder The form builder
     * @param array                $options The options
     */
    public function addReturnControlField(FormBuilderInterface $builder, array $options)
    {
        if ($options['mode'] != 'create') {
            return;
        }
        $builder->add('repeatCreation', 'Symfony\Component\Form\Extension\Core\Type\CheckboxType', [
            'mapped' => false,
            'label' => $this->__('Create another item after save'),
            'required' => false
        ]);
    }

    /**
     * Adds submit buttons.
     *
     * @param FormBuilderInterface $builder The form builder
     * @param array                $options The options
     */
    public function addSubmitButtons(FormBuilderInterface $builder, array $options)
    {
        foreach ($options['actions'] as $action) {
            $builder->add($action['id'], 'Symfony\Component\Form\Extension\Core\Type\SubmitType', [
                'label' => $this->__(/** @Ignore */$action['title']),
                'icon' => ($action['id'] == 'delete' ? 'fa-trash-o' : ''),
                'attr' => [
                    'class' => $action['buttonClass'],
                    'title' => $this->__(/** @Ignore */$action['description'])
                ]
            ]);
        }
        $builder->add('reset', 'Symfony\Component\Form\Extension\Core\Type\ResetType', [
            'label' => $this->__('Reset'),
            'icon' => 'fa-refresh',
            'attr' => [
                'class' => 'btn btn-default',
                'formnovalidate' => 'formnovalidate'
            ]
        ]);
        $builder->add('cancel', 'Symfony\Component\Form\Extension\Core\Type\SubmitType', [
            'label' => $this->__('Cancel'),
            'icon' => 'fa-times',
            'attr' => [
                'class' => 'btn btn-default',
                'formnovalidate' => 'formnovalidate'
            ]
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'rkreferencemodule_activity';
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver
            ->setDefaults([
                // define class for underlying data (required for embedding forms)
                'data_class' => 'RK\ReferenceModule\Entity\ActivityEntity',
                'empty_data' => function (FormInterface $form) {
                    return $this->entityFactory->createActivity();
                },
                'error_mapping' => [
                    'titleImage' => 'titleImage.titleImage',
                    'referenceImage' => 'referenceImage.referenceImage',
                ],
                'mode' => 'create',
                'actions' => [],
                'has_moderate_permission' => false,
                'filter_by_ownership' => true,
                'inline_usage' => false
            ])
            ->setRequired(['entity', 'mode', 'actions'])
            ->setAllowedTypes([
                'mode' => 'string',
                'actions' => 'array',
                'has_moderate_permission' => 'bool',
                'filter_by_ownership' => 'bool',
                'inline_usage' => 'bool'
            ])
            ->setAllowedValues([
                'mode' => ['create', 'edit']
            ])
        ;
    }
}
