<?php
/**
 * Reference.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\ReferenceModule\Entity;

use RK\ReferenceModule\Entity\Base\AbstractAttachedImageEntity as BaseEntity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Validator\Constraints as Assert;
use RK\ReferenceModule\Traits\EntityWorkflowTrait;
use RK\ReferenceModule\Traits\StandardFieldsTrait;

/**
 * Entity class that defines the entity structure and behaviours.
 *
 * This is the concrete entity class for attached image entities.
 * @ORM\Entity(repositoryClass="RK\ReferenceModule\Entity\Repository\AttachedImageRepository")
 * @ORM\Table(name="rk_refere_attachedimage",
 *     indexes={
 *         @ORM\Index(name="workflowstateindex", columns={"workflowState"})
 *     }
 * )
 */
class AttachedImageEntity extends BaseEntity
{
    // feel free to add your own methods here
}
