<?php
/**
 * Info.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.1 (http://modulestudio.de).
 */

namespace RK\InfoModule\Api;

use RK\InfoModule\Api\Base\AbstractMailzApi;

/**
 * Mailz api implementation class.
 */
class MailzApi extends AbstractMailzApi
{
    // feel free to extend the mailz api here
}
