<?php
/**
 * Info.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.1 (http://modulestudio.de).
 */

namespace RK\InfoModule\Form\Type\Finder;

use RK\InfoModule\Form\Type\Finder\Base\AbstractInformationFinderType;

/**
 * Information finder form type implementation class.
 */
class InformationFinderType extends AbstractInformationFinderType
{
    // feel free to extend the base form type class here
}
