<?php
/**
 * Reference.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\ReferenceModule;

use RK\ReferenceModule\Base\AbstractRKReferenceModule;

/**
 * Module implementation class.
 */
class RKReferenceModule extends AbstractRKReferenceModule
{
    // custom enhancements can go here
}
