<?php
/**
 * Info.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\InfoModule\Entity\Factory;

use RK\InfoModule\Entity\Factory\Base\AbstractInfoFactory;

/**
 * Factory class used to create entities and receive entity repositories.
 *
 * This is the concrete factory class.
 */
class InfoFactory extends AbstractInfoFactory
{
    // feel free to customise the factory
}
