<?php
/**
 * Reference.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\ReferenceModule\Event;

use RK\ReferenceModule\Event\Base\AbstractFilterAttachedImageEvent;

/**
 * Event implementation class for filtering attached image processing.
 */
class FilterAttachedImageEvent extends AbstractFilterAttachedImageEvent
{
    // feel free to extend the event class here
}
