<?php
/**
 * Info.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.1 (http://modulestudio.de).
 */

/**
 * Replaces a given needle id by the corresponding content.
 *
 * @param array $args Arguments array
 *     int nid The needle id
 *
 * @return string Replaced value for the needle
 */
function RKInfoModule_needleapi_information_base($args)
{
    // Get arguments from argument array
    $nid = $args['nid'];
    unset($args);

    // cache the results
    static $cache;
    if (!isset($cache)) {
        $cache = [];
    }

    $translator = \ServiceUtil::get('translator.default');

    if (empty($nid)) {
        return '<em>' . \DataUtil::formatForDisplay(__('No correct needle id given.')) . '</em>';
    }

    if (isset($cache[$nid])) {
        // needle is already in cache array
        return $cache[$nid];
    }

    if (!\ServiceUtil::get('kernel')->isBundle('RKInfoModule')) {
        $cache[$nid] = '<em>' . \DataUtil::formatForDisplay($translator->__f('Module %s is not available.', ['%s' => RKInfoModule'])) . '</em>';

        return $cache[$nid];
    }

    // strip application prefix from needle
    $needleId = str_replace('INFO', '', $nid);

    $router = \ServiceUtil::getService('router');

    if ($needleId == 'INFORMATIONS') {
        if (!\SecurityUtil::checkPermission('RKInfoModule:Information:', '::', ACCESS_READ)) {
            $cache[$nid] = '';

            return $cache[$nid];
        }
    }

    $cache[$nid] = '<a href="' . $router->generate('rkinfomodule_informations_view') . '" title="' . $translator->__('View informations') . '">' . $translator->__('Informations') . '</a>';
    $needleParts = explode('-', $needleId);
    if ($needleParts[0] != 'INFORMATION' || count($needleParts) < 2) {
        $cache[$nid] = '';

        return $cache[$nid];
    }

    $permissionApi = \ServiceUtil::get('zikula_permissions_module.api.permission');
    $entityId = (int)$needleParts[1];

    if (!$permissionApi->hasPermission('RKInfoModule:Information:', $entityId . '::', ACCESS_READ)) {
        $cache[$nid] = '';

        return $cache[$nid];
    }

    $selectionHelper = \ServiceUtil::get('rk_info_module.selection_helper');
    $entity = $selectionHelper->getEntity('information', $entityId);
    if (null === $entity) {
        $cache[$nid] = '<em>' . $translator->__f('Information with id %s could not be found', ['%s' => $entityId]) . '</em>';

        return $cache[$nid];
    }

    $title = $entity->getTitleFromDisplayPattern();
    $cache[$nid] = '<a href="' . $router->generate('rkinfomodule_informations_display', ['id' => $entityId]) . '" title="' . str_replace('"', '', $title) . '">' . $title . '</a>';

    return $cache[$nid];
}
