<?php
/**
 * Info.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\InfoModule\Form\Handler\Information;

use RK\InfoModule\Form\Handler\Information\Base\AbstractEditHandler;

/**
 * This handler class handles the page events of the Form called by the rKInfoModule_information_edit() function.
 * It aims on the information object type.
 */
class EditHandler extends AbstractEditHandler
{
    // feel free to extend the base handler class here
}
