services:
    rk_info_module.link_container:
        class: RK\InfoModule\Container\LinkContainer
        arguments:
            - "@translator.default"
            - "@router"
            - "@zikula_permissions_module.api.permission"
            - "@zikula_users_module.current_user"
            - "@rk_info_module.controller_helper"
        tags:
            - { name: zikula.link_container }
