<?php
/**
 * Reference.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\ReferenceModule;

use RK\ReferenceModule\Base\AbstractReferenceModuleInstaller;

/**
 * Installer implementation class.
 */
class ReferenceModuleInstaller extends AbstractReferenceModuleInstaller
{
    // feel free to extend the installer here
}
